-- Oracle의 GRANT CONNECT, RESOURCE TO HR; 는 MySQL에서 따로 적용하지 않음

CREATE TABLE CAR_USER (
    CAR_NO VARCHAR(20) PRIMARY KEY,
    REG_DATE DATE NOT NULL,
    LAST_USED DATE,
    IS_AGREED CHAR(1) NOT NULL CHECK (IS_AGREED IN ('Y','N')),
    INPUT_METHOD VARCHAR(10) NOT NULL CHECK (INPUT_METHOD IN ('AUTO', 'MANUAL'))
);
alter table car_user
add   VEHCLE_IMAGE_PA VARCHAR(255);
select * FROM CAR_USER;

CREATE TABLE PAYMENT_METHOD (
    CARD_NO VARCHAR(20) PRIMARY KEY,
    EXP_DATE VARCHAR(5) NOT NULL,
    CARD_ISSUER VARCHAR(30) NOT NULL,
    CAR_NO VARCHAR(20) NOT NULL,
    PAY_TYPE VARCHAR(20) NOT NULL CHECK (PAY_TYPE IN ('CARD','PAY')),
    CONSTRAINT FK_PAYMENT_USER FOREIGN KEY (CAR_NO) REFERENCES CAR_USER(CAR_NO)
);

CREATE TABLE CHARGER_POINT (
    CHARGER_ID INT PRIMARY KEY,
    CHARGER_NAME VARCHAR(50) NOT NULL,
    AREA_ID INT NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CHARGER_COUNT INT NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE TABLE CHARGER_UNIT (
    UNIT_ID INT PRIMARY KEY,
    CHARGER_ID INT NOT NULL,
    STATUS VARCHAR(10) NOT NULL CHECK (STATUS IN ('사용가능','사용중','고장')),
    POWER_KW INT NOT NULL,
    CHARGER_TYPE VARCHAR(20) NOT NULL,
    FOREIGN KEY (CHARGER_ID) REFERENCES CHARGER_POINT(CHARGER_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CARD_NO VARCHAR(20) NOT NULL,
    CAR_NO VARCHAR(20) NOT NULL,
    FOREIGN KEY (CARD_NO) REFERENCES PAYMENT_METHOD(CARD_NO),
    FOREIGN KEY (CAR_NO) REFERENCES CAR_USER(CAR_NO)
);

CREATE TABLE CHARGE_LOG (
    LOG_ID INT PRIMARY KEY,
    CAR_NO VARCHAR(20) NOT NULL,
    UNIT_ID INT NOT NULL,
    START_TIME DATE NOT NULL,
    END_TIME DATE,
    POWER_USED DECIMAL(6,2),
    PAYMENT_ID INT UNIQUE,
    IS_SUCCESS CHAR(1) NOT NULL CHECK (IS_SUCCESS IN ('Y','N')),
    FOREIGN KEY (UNIT_ID) REFERENCES CHARGER_UNIT(UNIT_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);


ALTER TABLE CHARGE_LOG
ADD (
	ENTRY_IMAGE_PATH VARCHAR(255),
    ENTRY_TIME DATETIME,
    EXIT_IMAGE_PATH VARCHAR(255),
    EXIT_TIME DATETIME
);
SELECT * FROM CHARGE_LOG;     

CREATE TABLE FACILITY (
    FACILITY_ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CHARGER_ID INT NOT NULL,
    FOREIGN KEY (CHARGER_ID) REFERENCES CHARGER_POINT(CHARGER_ID)
);

CREATE TABLE ADMINS (
    ADMIN_ID INT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE ADMIN_CALL (
    CALL_ID INT PRIMARY KEY,
    CAR_NO VARCHAR(20) NOT NULL,
    CALL_TIME DATE NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    ADMIN_ID INT,
    RESOLVED_TIME DATE,
    STATUS VARCHAR(10) NOT NULL CHECK (STATUS IN ('대기','완료')),
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMINS(ADMIN_ID)
);

CREATE TABLE PERSONAL_DATA_CONSENT (
    CONSENT_ID INT PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    CONSENT_GIVEN CHAR(1) NOT NULL CHECK (CONSENT_GIVEN IN ('Y','N')),
    CONSENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSENT_TYPE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_CONSENT_USER FOREIGN KEY (USER_ID) REFERENCES CAR_USER(CAR_NO)
);


